project_id = "obdwvgxxunkomacbifry"

[functions.create-appointment]
verify_jwt = true

[functions.list-appointments] 
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.secure-webhook]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.api-me]
verify_jwt = false

[functions.user-data]
verify_jwt = false

[functions.ping]
verify_jwt = false

[functions.diag-env]
verify_jwt = false

[functions.mp-validate]
verify_jwt = false

[functions.diag-secret]
verify_jwt = false

[functions.db-health]
verify_jwt = false

[functions.test-prod-connection]
verify_jwt = false

[functions.whoami]
verify_jwt = false

[functions.reconcile-subscriptions]
verify_jwt = false

[functions.auth-ping]
verify_jwt = true

[functions.create-onboarding-token]
verify_jwt = false

[functions.diagnostic-reset]
verify_jwt = false

[functions.mp-methods]
verify_jwt = false

[functions.test-mercadopago]
verify_jwt = false

[functions.test-reset-flow]
verify_jwt = false

[functions.validate-onboarding-token]
verify_jwt = false