project_id = "obdwvgxxunkomacbifry"

[functions.create-appointment]
verify_jwt = true

[functions.list-appointments] 
verify_jwt = true

[functions.materialize-recurring]
verify_jwt = true

[functions.diag-create-client]
verify_jwt = true

[functions.diag-create-cliente-recorrente]
verify_jwt = true

[functions.test-client-create-flow]
verify_jwt = true

[functions.mercadopago-webhook]
verify_jwt = false

[functions.secure-webhook]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.api-me]
verify_jwt = false

[functions.user-data]
verify_jwt = false

[functions.reconcile-subscriptions]
verify_jwt = false

[functions.auth-ping]
verify_jwt = true

[functions.create-onboarding-token]
verify_jwt = false

[functions.diagnostic-reset]
verify_jwt = false

[functions.diag-digest-fix]
verify_jwt = true

[functions.mp-methods]
verify_jwt = false

[functions.validate-onboarding-token]
verify_jwt = false

[functions.log-rpc-usage]
verify_jwt = false