project_id = "obdwvgxxunkomacbifry"

[functions.mercadopago-webhook]
verify_jwt = false

[functions.secure-webhook]
verify_jwt = false

[functions.create-subscription]
verify_jwt = true

[functions.api-me]
verify_jwt = false

[functions.user-data]
verify_jwt = false

[functions.ping]
verify_jwt = false

[functions.diag-env]
verify_jwt = false

[functions.mp-validate]
verify_jwt = false

[functions.diag-secret]
verify_jwt = false

[functions.db-health]
verify_jwt = false

[functions.auth-ping]
verify_jwt = false