-- Create mp_subscriptions table for proper subscription management
create table if not exists public.mp_subscriptions (
  id bigint generated by default as identity primary key,
  user_id uuid not null,
  plan text not null check (plan in ('monthly','annual')),
  external_reference text not null,
  mp_preapproval_id text,
  init_point text,
  status text not null default 'pending',
  raw_response jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Create unique index on external_reference
create unique index if not exists mp_subscriptions_external_ref_uidx on public.mp_subscriptions(external_reference);

-- Enable RLS
alter table public.mp_subscriptions enable row level security;

-- Policy for users to read their own subscriptions
create policy "user can read own subs" on public.mp_subscriptions
  for select using (auth.uid() = user_id);

-- Policy for service role to manage all subscriptions (admin operations)
create policy "service role can manage all subs" on public.mp_subscriptions
  for all using (true);